

lab2:
	echo "running program Ex1.5\n"
	make compile-file f="ex15"
	echo "running program Ex1.11\n"
	# echo "using 1, 10 as arguments\n"
	make compile-file f="ex11"
	

compile-file: 
	g++ ${f}.cpp -o ${f} 
	./${f}







